from __future__ import annotations

import argparse
import sys
from pathlib import Path

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

SRC_DIR = Path(__file__).resolve().parents[1]
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from solar_model import SolarModel


GPS_DEFAULT = "outputs/gps_2026-06-09_to_2026-06-12.csv"
MPPT_DEFAULT = "outputs/mppt_with_status_2026-06-09_to_2026-06-12.csv"

OUT_CSV = "outputs/solar_model_vs_mppt_2026-06-09_to_2026-06-12.csv"
OUT_TIME_PNG = "outputs/solar_model_vs_mppt_timeseries.png"
OUT_SCATTER_PNG = "outputs/solar_model_vs_mppt_scatter.png"


def load_gps(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    df["_time"] = pd.to_datetime(df["_time"], utc=True, errors="coerce")

    required = [
        "_time",
        "VCU_GPS_Latitude",
        "VCU_GPS_Longitude",
    ]
    missing = [column for column in required if column not in df.columns]
    if missing:
        raise ValueError(f"GPS CSV is missing columns: {missing}")

    df = df.dropna(subset=required).copy()
    df = df[
        df["VCU_GPS_Latitude"].between(-90, 90)
        & df["VCU_GPS_Longitude"].between(-180, 180)
        & (df["VCU_GPS_Latitude"] != 0)
        & (df["VCU_GPS_Longitude"] != 0)
    ]

    if "VCU_GPS_Active" in df.columns:
        df = df[df["VCU_GPS_Active"] == 1]

    if "VCU_GPS_FixQuality" in df.columns:
        df = df[df["VCU_GPS_FixQuality"] > 0]

    return df.sort_values("_time").reset_index(drop=True)


def load_mppt(path: str, min_active_mppts: int) -> pd.DataFrame:
    df = pd.read_csv(path)
    df["_time"] = pd.to_datetime(df["_time"], utc=True, errors="coerce")
    df = df.dropna(subset=["_time"]).copy()

    required = ["active_mppt_count", "measured_solar_power_w"]
    missing = [column for column in required if column not in df.columns]
    if missing:
        raise ValueError(
            f"MPPT CSV is missing columns: {missing}. "
            "Use the CSV generated by tools/check_mppt_history.py."
        )

    df["active_mppt_count"] = pd.to_numeric(
        df["active_mppt_count"],
        errors="coerce",
    )
    df["measured_solar_power_w"] = pd.to_numeric(
        df["measured_solar_power_w"],
        errors="coerce",
    )

    df = df[
        (df["active_mppt_count"] >= min_active_mppts)
        & df["measured_solar_power_w"].notna()
    ].copy()

    return df.sort_values("_time").reset_index(drop=True)


def aggregate_per_minute(
    gps: pd.DataFrame,
    mppt: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    gps = gps.set_index("_time")
    mppt = mppt.set_index("_time")

    gps_agg = {
        "VCU_GPS_Latitude": "median",
        "VCU_GPS_Longitude": "median",
    }

    if "VCU_GPS_Speed" in gps.columns:
        gps_agg["VCU_GPS_Speed"] = "mean"

    if "VCU_GPS_Altitude" in gps.columns:
        gps_agg["VCU_GPS_Altitude"] = "median"

    gps_minute = (
        gps.resample("1min")
        .agg(gps_agg)
        .dropna(subset=["VCU_GPS_Latitude", "VCU_GPS_Longitude"])
        .reset_index()
    )

    mppt_agg = {
        "measured_solar_power_w": "median",
        "active_mppt_count": "max",
    }

    for index in range(1, 5):
        column = f"MPPT{index}_MeasuredPower_W"
        if column in mppt.columns:
            mppt_agg[column] = "median"

    mppt_minute = (
        mppt.resample("1min")
        .agg(mppt_agg)
        .dropna(subset=["measured_solar_power_w"])
        .reset_index()
    )

    return gps_minute, mppt_minute


def distance_to_track_m(
    model: SolarModel,
    track: str,
    lat: float,
    lon: float,
) -> tuple[int, float]:
    track_df, _ = model.load_track(track)

    point_id = model.nearest_point_id(
        track=track,
        lat=lat,
        lon=lon,
    )

    row = track_df[track_df["point_id"] == point_id].iloc[0]

    car = gpd.GeoDataFrame(
        {"id": [1]},
        geometry=gpd.points_from_xy([lon], [lat]),
        crs="EPSG:4326",
    ).to_crs("EPSG:3857")

    dx = float(row["x_m"]) - float(car.geometry.x.iloc[0])
    dy = float(row["y_m"]) - float(car.geometry.y.iloc[0])

    return point_id, float(np.hypot(dx, dy))


def calculate_metrics(df: pd.DataFrame) -> dict:
    measured = df["measured_solar_power_w"].to_numpy(dtype=float)
    calculated = df["calculated_solar_power_w"].to_numpy(dtype=float)

    residual = measured - calculated

    mae = float(np.mean(np.abs(residual)))
    rmse = float(np.sqrt(np.mean(residual ** 2)))

    denominator = float(np.sum((measured - np.mean(measured)) ** 2))
    r2 = (
        float(1 - np.sum(residual ** 2) / denominator)
        if denominator > 0
        else float("nan")
    )

    return {
        "mae_w": mae,
        "rmse_w": rmse,
        "r2": r2,
    }


def save_time_series(df: pd.DataFrame, path: str) -> None:
    fig, ax = plt.subplots(figsize=(12, 6))

    ax.plot(
        df["timestamp_utc"],
        df["calculated_solar_power_w"],
        label="Calculated solar power",
    )
    ax.plot(
        df["timestamp_utc"],
        df["measured_solar_power_w"],
        label="Measured MPPT power",
    )

    ax.set_xlabel("Timestamp")
    ax.set_ylabel("Power (W)")
    ax.set_title("Solar model vs measured MPPT power")
    ax.grid(True)
    ax.legend()

    fig.autofmt_xdate()
    fig.tight_layout()

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=200)
    plt.close(fig)


def save_scatter(df: pd.DataFrame, path: str) -> None:
    measured = df["measured_solar_power_w"]
    calculated = df["calculated_solar_power_w"]

    fig, ax = plt.subplots(figsize=(7, 7))

    ax.scatter(measured, calculated)

    minimum = float(min(measured.min(), calculated.min()))
    maximum = float(max(measured.max(), calculated.max()))
    ax.plot(
        [minimum, maximum],
        [minimum, maximum],
        linestyle="--",
        label="Perfect agreement",
    )

    ax.set_xlabel("Measured MPPT power (W)")
    ax.set_ylabel("Calculated solar power (W)")
    ax.set_title("Measured vs calculated solar power")
    ax.grid(True)
    ax.legend()
    fig.tight_layout()

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=200)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compare SolarModel output with status-valid MPPT telemetry."
    )

    parser.add_argument("--track", default="bucharest")
    parser.add_argument("--gps-csv", default=GPS_DEFAULT)
    parser.add_argument("--mppt-csv", default=MPPT_DEFAULT)
    parser.add_argument("--output-csv", default=OUT_CSV)
    parser.add_argument("--output-time-png", default=OUT_TIME_PNG)
    parser.add_argument("--output-scatter-png", default=OUT_SCATTER_PNG)

    parser.add_argument(
        "--max-distance-from-track-m",
        type=float,
        default=500.0,
    )
    parser.add_argument(
        "--min-active-mppts",
        type=int,
        default=1,
        choices=[1, 2, 3, 4],
    )

    args = parser.parse_args()

    gps = load_gps(args.gps_csv)
    mppt = load_mppt(
        args.mppt_csv,
        min_active_mppts=args.min_active_mppts,
    )

    gps_minute, mppt_minute = aggregate_per_minute(gps, mppt)

    merged = pd.merge_asof(
        gps_minute.sort_values("_time"),
        mppt_minute.sort_values("_time"),
        on="_time",
        direction="nearest",
        tolerance=pd.Timedelta("59s"),
    ).dropna(subset=["measured_solar_power_w"])

    model = SolarModel(use_weather_api=False)
    rows = []

    for _, sample in merged.iterrows():
        lat = float(sample["VCU_GPS_Latitude"])
        lon = float(sample["VCU_GPS_Longitude"])

        point_id, distance_m = distance_to_track_m(
            model=model,
            track=args.track,
            lat=lat,
            lon=lon,
        )

        if distance_m > args.max_distance_from_track_m:
            continue

        estimated = model.get_solar_input(
            track=args.track,
            timestamp=sample["_time"],
            point_id=point_id,
        )

        measured = float(sample["measured_solar_power_w"])
        calculated = float(estimated["solar_power_w"])
        error = measured - calculated

        row = {
            "timestamp_utc": sample["_time"],
            "gps_latitude": lat,
            "gps_longitude": lon,
            "point_id": point_id,
            "distance_to_track_m": distance_m,
            "active_mppt_count": int(sample["active_mppt_count"]),
            "calculated_solar_power_w": calculated,
            "measured_solar_power_w": measured,
            "error_w": error,
            "absolute_error_w": abs(error),
            "error_percent": (
                error / calculated * 100.0
                if calculated > 1e-9
                else np.nan
            ),
            "irradiance_wm2": float(estimated["irradiance_wm2"]),
            "shadow_factor": float(estimated["shadow_factor"]),
            "orientation_factor": float(estimated["orientation_factor"]),
            "pitch_factor": float(estimated["pitch_factor"]),
            "weather_source": estimated["weather_source"],
        }

        for index in range(1, 5):
            column = f"MPPT{index}_MeasuredPower_W"
            if column in sample.index:
                row[column] = sample[column]

        rows.append(row)

    comparison = pd.DataFrame(rows)

    if comparison.empty:
        print(
            "No synchronized GPS/MPPT samples were found "
            "near the selected track."
        )
        return

    output_csv = Path(args.output_csv)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    comparison.to_csv(output_csv, index=False)

    save_time_series(comparison, args.output_time_png)
    save_scatter(comparison, args.output_scatter_png)

    metrics = calculate_metrics(comparison)

    print(f"Valid GPS rows: {len(gps)}")
    print(f"Status-valid MPPT rows: {len(mppt)}")
    print(f"GPS minute samples: {len(gps_minute)}")
    print(f"MPPT minute samples: {len(mppt_minute)}")
    print(f"Comparison rows: {len(comparison)}")

    print(
        f"Mean calculated power: "
        f"{comparison['calculated_solar_power_w'].mean():.2f} W"
    )
    print(
        f"Mean measured power: "
        f"{comparison['measured_solar_power_w'].mean():.2f} W"
    )
    print(f"MAE: {metrics['mae_w']:.2f} W")
    print(f"RMSE: {metrics['rmse_w']:.2f} W")
    print(f"R²: {metrics['r2']:.4f}")

    print(f"Saved CSV: {output_csv}")
    print(f"Saved time-series chart: {args.output_time_png}")
    print(f"Saved scatter chart: {args.output_scatter_png}")


if __name__ == "__main__":
    main()
